#!/usr/bin/env python
import sys
import os

BASE_DIR = os.path.abspath( os.path.join( os.path.dirname( __file__ ), ".." ) )
path     = os.path.abspath( os.path.join( BASE_DIR, "python" ) )
sys.path.append( path )

import numpy as np
import pylab as pl
import momo

width = 150
height = 50
radius = 10
cell_size = 1

convert = momo.convert( { "x1": 0, "y1": 0, "x2": width, "y2": height }, cell_size )
compute_features = momo.features.test.compute_features( convert, radius = radius )

frame = np.array( [
  [15.0, 15.0, 0.0, 0.0], 
  [135.0, 35.0, 0.0, 0.0]
] )

features = compute_features( frame )

pl.imshow( features[0], pl.cm.jet, None, None, "none" )
pl.show()
